In [1]:
import pandas

In [5]:
movies = pandas.read_csv('../data/movies.csv', sep='|', 
                         usecols=[0,1], names=['movie_id', 'title']
                        )
movies

      movie_id                                              title
0            1                                   Toy Story (1995)
1            2                                   GoldenEye (1995)
2            3                                  Four Rooms (1995)
3            4                                  Get Shorty (1995)
4            5                                     Copycat (1995)
5            6  Shanghai Triad (Yao a yao yao dao waipo qiao) ...
6            7                              Twelve Monkeys (1995)
7            8                                        Babe (1995)
8            9                            Dead Man Walking (1995)
9           10                                 Richard III (1995)
10          11                               Seven (Se7en) (1995)
11          12                         Usual Suspects, The (1995)
12          13                            Mighty Aphrodite (1995)
13          14                                 Postino, Il (1994)
14          15                          Mr. Holland's Opus (1995)
15          16                 French Twist (Gazon maudit) (1995)
16          17                         From Dusk Till Dawn (1996)
17          18                          White Balloon, The (1995)
18          19                              Antonia's Line (1995)
19          20                          Angels and Insects (1995)
20          21                      Muppet Treasure Island (1996)
21          22                                  Braveheart (1995)
22          23                                 Taxi Driver (1976)
23          24                         Rumble in the Bronx (1995)
24          25                               Birdcage, The (1996)
25          26                      Brothers McMullen, The (1995)
26          27                                    Bad Boys (1995)
27          28                                   Apollo 13 (1995)
28          29                              Batman Forever (1995)
29          30                               Belle de jour (1967)
...        ...                                                ...
1652      1653  Entertaining Angels: The Dorothy Day Story (1996)
1653      1654                       Chairman of the Board (1998)
1654      1655                                  Favor, The (1994)
1655      1656                                 Little City (1998)
1656      1657                                      Target (1995)
1657      1658                      Substance of Fire, The (1996)
1658      1659                    Getting Away With Murder (1996)
1659      1660                                 Small Faces (1995)
1660      1661                                New Age, The (1994)
1661      1662                                 Rough Magic (1995)
1662      1663                            Nothing Personal (1995)
1663      1664                     8 Heads in a Duffel Bag (1997)
1664      1665                           Brother's Kiss, A (1997)
1665      1666                                        Ripe (1996)
1666      1667                              Next Step, The (1995)
1667      1668                          Wedding Bell Blues (1996)
1668      1669                           MURDER and murder (1996)
1669      1670                                     Tainted (1998)
1670      1671                          Further Gesture, A (1996)
1671      1672                                        Kika (1993)
1672      1673                                      Mirage (1995)
1673      1674                                  Mamma Roma (1962)
1674      1675                              Sunchaser, The (1996)
1675      1676                            War at Home, The (1996)
1676      1677                               Sweet Nothing (1995)
1677      1678                                  Mat' i syn (1997)
1678      1679                                   B. Monkey (1998)
1679      1680                               Sliding Doors (1998)
1680      1681                                You So Crazy (1994)
1681      1682          Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [9]:
ratings = pandas.read_csv('../data/movie-ratings.txt', sep='\t',
                         names=['user_id', 'movie_id', 'rating', 'timestamp'])
ratings

       user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
5          298       474       4  884182806
6          115       265       2  881171488
7          253       465       5  891628467
8          305       451       3  886324817
9            6        86       3  883603013
10          62       257       2  879372434
11         286      1014       5  879781125
12         200       222       5  876042340
13         210        40       3  891035994
14         224        29       3  888104457
15         303       785       3  879485318
16         122       387       5  879270459
17         194       274       2  879539794
18         291      1042       4  874834944
19         234      1184       2  892079237
20         119       392       4  886176814
21         167       486       4  892738452
22         299       144       4  877881320
23         291       118       2  874833878
24         308         1       4  887736532
25          95       546       2  879196566
26          38        95       5  892430094
27         102       768       2  883748450
28          63       277       4  875747401
29         160       234       5  876861185
...        ...       ...     ...        ...
99970      449       120       1  879959573
99971      661       762       2  876037121
99972      721       874       3  877137447
99973      821       151       4  874792889
99974      764       596       3  876243046
99975      537       443       3  886031752
99976      618       628       2  891308019
99977      487       291       3  883445079
99978      113       975       5  875936424
99979      943       391       2  888640291
99980      864       685       4  888891900
99981      750       323       3  879445877
99982      279        64       1  875308510
99983      646       750       3  888528902
99984      654       370       2  887863914
99985      617       582       4  883789294
99986      913       690       3  880824288
99987      660       229       2  891406212
99988      421       498       4  892241344
99989      495      1091       4  888637503
99990      806       421       4  882388897
99991      676       538       4  892685437
99992      721       262       3  877137285
99993      913       209       2  881367150
99994      378        78       3  880056976
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [20]:
one_slope_df = pandas.DataFrame({
        'title' : movies.set_index('movie_id').title,
        'ratings_counts': ratings.groupby('movie_id').rating.count(),
        'mean_rating': ratings.groupby('movie_id').rating.mean()
        })
one_slope_df

,mean_rating,ratings_counts,title
movie_id,,,
1,3.878319,452,Toy Story (1995)
2,3.206107,131,GoldenEye (1995)
3,3.033333,90,Four Rooms (1995)
4,3.550239,209,Get Shorty (1995)
5,3.302326,86,Copycat (1995)
6,3.576923,26,Shanghai Triad (Yao a yao yao dao waipo qiao) ...
7,3.798469,392,Twelve Monkeys (1995)
8,3.995434,219,Babe (1995)
9,3.896321,299,Dead Man Walking (1995)
10,3.831461,89,Richard III (1995)
11,3.847458,236,Seven (Se7en) (1995)
12,4.385768,267,"Usual Suspects, The (1995)"
13,3.418478,184,Mighty Aphrodite (1995)
14,3.967213,183,"Postino, Il (1994)"
15,3.778157,293,Mr. Holland's Opus (1995)
16,3.205128,39,French Twist (Gazon maudit) (1995)
17,3.119565,92,From Dusk Till Dawn (1996)
18,2.800000,10,"White Balloon, The (1995)"
19,3.956522,69,Antonia's Line (1995)
20,3.416667,72,Angels and Insects (1995)
21,2.761905,84,Muppet Treasure Island (1996)
22,4.151515,297,Braveheart (1995)
23,4.120879,182,Taxi Driver (1976)
24,3.448276,174,Rumble in the Bronx (1995)
25,3.443686,293,"Birdcage, The (1996)"
26,3.452055,73,"Brothers McMullen, The (1995)"
27,3.105263,57,Bad Boys (1995)
28,3.931159,276,Apollo 13 (1995)
29,2.666667,114,Batman Forever (1995)
30,3.945946,37,Belle de jour (1967)
...,...,...,...
1653,5.000000,1,Entertaining Angels: The Dorothy Day Story (1996)
1654,1.000000,1,Chairman of the Board (1998)
1655,2.000000,1,"Favor, The (1994)"
1656,3.500000,2,Little City (1998)
1657,3.000000,1,Target (1995)
1658,3.000000,3,"Substance of Fire, The (1996)"
1659,1.000000,1,Getting Away With Murder (1996)
1660,2.000000,1,Small Faces (1995)
1661,1.000000,1,"New Age, The (1994)"
1662,2.500000,2,Rough Magic (1995)
1663,2.000000,1,Nothing Personal (1995)
1664,3.250000,4,8 Heads in a Duffel Bag (1997)
1665,2.000000,1,"Brother's Kiss, A (1997)"
1666,2.000000,1,Ripe (1996)
1667,3.000000,1,"Next Step, The (1995)"
1668,3.000000,1,Wedding Bell Blues (1996)
1669,2.000000,1,MURDER and murder (1996)
1670,3.000000,1,Tainted (1998)
1671,1.000000,1,"Further Gesture, A (1996)"
1672,2.000000,2,Kika (1993)
1673,3.000000,1,Mirage (1995)
1674,4.000000,1,Mamma Roma (1962)
1675,3.000000,1,"Sunchaser, The (1996)"
1676,2.000000,1,"War at Home, The (1996)"
1677,3.000000,1,Sweet Nothing (1995)
1678,1.000000,1,Mat' i syn (1997)
1679,3.000000,1,B. Monkey (1998)
1680,2.000000,1,Sliding Doors (1998)
1681,3.000000,1,You So Crazy (1994)
1682,3.000000,1,Scream of Stone (Schrei aus Stein) (1991)

In [25]:
one_slope_df.loc[one_slope_df[one_slope_df.ratings_counts > 25].mean_rating.idxmax()]

mean_rating                     4.49107
ratings_counts                      112
title             Close Shave, A (1995)
Name: 408, dtype: object

In [29]:
ratings[ratings.movie_id != 408].user_id.value_counts()

405    737
655    685
13     636
450    540
276    517
416    493
537    490
303    483
234    480
393    448
181    434
279    433
429    414
846    405
7      403
94     400
682    399
308    396
293    388
92     387
222    387
201    385
59     382
435    379
378    375
880    368
417    365
896    362
592    359
796    358
      ...
418     20
242     20
558     20
685     20
812     20
364     20
300     20
631     20
873     20
809     20
166     20
740     20
36      20
866     20
34      20
143     20
824     20
888     20
926     20
441     20
93      20
732     20
475     20
571     20
596     20
147     20
19      20
572     20
636     20
895     20
Name: user_id, dtype: int64

In [ ]:
# what would user 405 think?

In [31]:
ratings[ratings.user_id == 405].rating.mean()

1.8344640434192674

In [32]:
ratings.rating.mean()

3.52986

In [34]:
user405_offset = ratings[ratings.user_id == 405].rating.mean() - ratings.rating.mean()
one_slope_df.loc[408].mean_rating + user405_offset

2.795675471990696

In [35]:
# in other words, grumpy user 405 will rate "A close shave" around 2.79 stars